name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v
        run: node -v

      - name: Install yarn
        run: npm install -g yarn
        
      - name: Install dependency
        run: yarn install
    
#       - name: Test
#         run: yarn test
#         env:
#           CI: true
          
      - name: Build
        run: yarn build
        env:
          CI: ""

      - name: zip create
        run: zip -qq -r ./build-fe.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://chatting-fe-bucket/build-fe.zip

      - name: Code Deploy
        run: aws deploy create-deployment
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --application-name chatting-code        
          --deployment-group-name chatting-fe-server
          --s3-location bucket=chatting-fe-bucket,key=build-fe.zip,bundleType=zip
